FROM elasticsearch:latest
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash -
RUN apt-get install -y nodejs
COPY package.json /VisualizationG5/
COPY mock_data/ /VisualizationG5/mock_data/
RUN npm install -g yarn
WORKDIR /VisualizationG5/
RUN yarn install
EXPOSE 9200
# Elasticsearch gets 30 seconds to start up before the mock data will be inserted.
CMD (sleep 30 && pwd && nodejs /VisualizationG5/mock_data/insert_to_elasticsearch.js) & \
    /usr/share/elasticsearch/bin/elasticsearch
