FROM node
COPY mock_data/ /VisualizationG5/mock_data/
COPY express/ /VisualizationG5/express/
WORKDIR /VisualizationG5/express/
RUN rm -rf node_modules/
RUN npm install -g forever
RUN yarn install
EXPOSE 3000
CMD ["npm", "run", "prod-fg"]
